# Generated by Django 2.0 on 2018-11-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ckeditor', '0003_auto_20181113_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
    ]
